<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>

<a href="/register">Register</a>
<form method="post" action="/login">
    <label for="username">Username: </label>
    <input id="username" name="username" value="Zhenya"/>
    <br/>
    <label for="passwd">Password: </label>
    <input id="passwd" name="password" value="qwerty"/>
    <button type="submit">Login</button>
</form>
</body>
</html>