DROP TABLE "Location" IF EXIST;

DROP TABLE "Fight" IF EXIST;

DROP TABLE "Song" IF EXIST;

DROP TABLE "Effect" IF EXIST;

DROP TABLE "Hero" IF EXIST;

DROP TABLE "Character" IF EXIST;

DROP TABLE "User" IF EXIST;

DROP TABLE "Fight_Participant" IF EXIST;